---
# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: font_body_20
  display_mode: dark   # or light
  text_color: color_primary_text
  bg_color: color_background
  button_on_color: color_accent
  button_off_color: color_outline
  icon_on_color: color_accent
  icon_off_color: color_secondary_text
  label_on_color: color_primary_text
  label_off_color: color_secondary_text
  button_text_color: color_primary_text

  # LCD back light modes - Code in backlight_time.yaml
  # Set Day mode - starts at Sunrise - screen at 100%
  touchscreen_daytime_brightness: "100%"
  # Set Evening mode -  starts at Sunset - screen at 50% (may need to be brighter for some screens)
  touchscreen_nighttime_brightness: "50%"
  # Set Night mode start time (default is midnight)
  touchscreen_night_hour: "23"      # Hour for night mode (0-23)
  touchscreen_night_minute: "30"    # Minute for night mode (0-59)
  # Set touchscreen idle timeout - In night mode back light goes off after this amount of time
  touchscreen_idle_timeout: "60s"
  # Screen Size
  screen_height: '480'
  screen_width: '480'

esphome:
  name: "guition-4848s040"
  friendly_name: "Guition 4848s040"
  comment: "Guition ESP32-S3-4848S040 480px * 480px Smart Screen"
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page
ota:
  - platform: esphome

logger:
  level: DEBUG

api:
  on_client_connected:
    - script.execute: time_update

packages:
  # Generic configuration for ESP32 screens
  # All the colors
  colors: !include esphome-lvgl-panel/common/palette_dark.yaml
  #colors: !include esphome-lvgl-panel/common/palette_light.yaml
  # Fonts you need
  fonts: !include esphome-lvgl-panel/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-lvgl-panel/common/mdi_glyph_substitutions.yaml
  # SDL has no Wi-Fi wifi: 
  wifi: !include esphome-lvgl-panel/common/wifi.yaml
  # Some basic sensors
  sensors: !include esphome-lvgl-panel/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include esphome-lvgl-panel/common/theme_style.yaml
  # Include if your touch screen has a backlight. Also sets the time from HA
  # *** ONLY INCLUDE ONE OF THE BELOW
  backlight: !include esphome-lvgl-panel/common/backlight_time.yaml
  #time: !include esphome-lvgl-panel/common/time_sntp.yaml
  #time: !include esphome-lvgl-panel/common/time_homeassistant.yaml
  # Harware description file
  hardware: !include esphome-lvgl-panel/hardware/guition-esp32-s3-4848s040.yaml

  # Basic boot screen with ESPHome logo and device diagnostic info
  loading_screen: !include esphome-lvgl-panel/pages/loading_480px.yaml
  info_screen: !include esphome-lvgl-panel/pages/info.yaml

  time_date_widget:
    !include
    file: esphome-lvgl-panel/modules/time_date/time_date_core.yaml

  ev_widget:
    !include
    file: esphome-lvgl-panel/modules/ev/ev_core.yaml
    vars:
      battery_level_entity: sensor.leaf_battery_level
      range_entity: sensor.leaf_range_ac_off
      charging_state_entity: binary_sensor.leaf_charging

  # Weather packages
  # Display weather forecast using direct HA action (no template sensor needed!)
  # Icons are included automatically in the action file
  weather_forecast_80: !include
    file: esphome-lvgl-panel/modules/weather/weather.yaml
    vars:
      size: 80
      weather_entity: weather.met_office_totton

# Styles for Weather forecast
.forecast_styles:
  - &now_forecast_obj_base
    width: 100%
    height: SIZE_CONTENT
    bg_color: color_background
    radius: 3
    pad_top: 2
    pad_bottom: 2
    layout:
      type: flex
      flex_flow: COLUMN
      flex_align_cross: center
      flex_align_track: center
      pad_column: 0
      pad_row: 2

  - &forecast_obj_base
    height: SIZE_CONTENT
    width: SIZE_CONTENT
    radius: 3
    pad_top: 2
    pad_bottom: 2
    layout:
      type: flex
      flex_flow: COLUMN
      flex_align_cross: center
      flex_align_track: center
      pad_column: 0
      pad_row: 2

  - &forecast_label_base
    text_font: font_body_24
    height: SIZE_CONTENT

  - &forecast_label_base_lo
    height: SIZE_CONTENT
    text_font: font_body_20
    text_color: dodgerblue

  - &forecast_image_base
    height: SIZE_CONTENT


lvgl:
  pages:
    - id: main_page
      layout: 12x12
      styles: page_style
      <<: !include esphome-lvgl-panel/modules/swipe_navigation/swipe_navigation.yaml
      bg_color: color_background
      widgets:
        - !include
            file: esphome-lvgl-panel/modules/time_date/time_date_widget.yaml
            vars: { row_pos: "0", column_pos: "0", row_span: "4", column_span: "6" }

        - !include
            file: esphome-lvgl-panel/modules/ev/ev_widget.yaml
            vars: { row_pos: "0", column_pos: "6", row_span: "4", column_span: "6" }

        - container:
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 4
            grid_cell_column_pos: 0
            grid_cell_row_span: 4
            grid_cell_column_span: 6
            #outline_width: 1   # debug
            #outline_color: red # debug
            widgets:
              - obj:
                  <<: *now_forecast_obj_base
                  widgets:
                    - label:
                        text: "Now"
                        text_color: color_primary_text
                        <<: *forecast_label_base
                    - image:
                        id: weather_condition_icon
                        src: unknown_80
                    - label:
                        id: weather_temperature_today
                        <<: *forecast_label_base
                        text: "---°"
                        text_color: color_primary_text

        - container:
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 8
            grid_cell_column_pos: 0
            grid_cell_row_span: 4
            grid_cell_column_span: 12
            #outline_width: 1   # debug code - This is for visualizing boundries remove for production
            #outline_color: red # debug code - This is for visualizing boundries remove for production
            layout: 1x4
            widgets:
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  widgets:
                    - label:
                        id: forecast_day_0
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_0
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_0
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_0
                              <<: *forecast_label_base_lo
                              text: "---°"
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  widgets:
                    - label:
                        id: forecast_day_1
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_1
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_1
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_1
                              <<: *forecast_label_base_lo
                              text: "---°"
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  widgets:
                    - label:
                        id: forecast_day_2
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_2
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_2
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_2
                              <<: *forecast_label_base_lo
                              text: "---°"
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 3
                  widgets:
                    - label:
                        id: forecast_day_3
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_3
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_3
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_3
                              <<: *forecast_label_base_lo
                              text: "---°"