---
# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: font_body_20
  display_mode: dark   # or light
  text_color: color_primary_text
  bg_color: color_background
  button_on_color: color_accent
  button_off_color: color_outline
  icon_on_color: color_accent
  icon_off_color: color_secondary_text
  label_on_color: color_primary_text
  label_off_color: color_secondary_text
  button_text_color: color_primary_text

  # LCD back light modes - Code in backlight_time.yaml
  # Set Day mode - starts at Sunrise - screen at 100%
  touchscreen_daytime_brightness: "100%"
  # Set Evening mode -  starts at Sunset - screen at 50% (may need to be brighter for some screens)
  touchscreen_nighttime_brightness: "50%"
  # Set Night mode start time (default is midnight)
  touchscreen_night_hour: "0"      # Hour for night mode (0-23)
  touchscreen_night_minute: "0"    # Minute for night mode (0-59)
  # Set touchscreen idle timeout - In night mode back light goes off after this amount of time
  touchscreen_idle_timeout: "60s"
  # Screen Size
  screen_height: '480'
  screen_width: '480'

  # LCD backlight modes - Code in backlight.yaml
  # Day mode is set to Sunrise
  # Evening mode is set to sunset
  # Set Night mode  at Midnight here
  screen_night_hour: "23"
  screen_night_minute: "0"
  screen_day_hour: "7"
  screen_day_minute: "0"

esphome:
  name: "guition-4848s040"
  friendly_name: "Guition 4848s040"
  comment: "Guition ESP32-S3-4848S040 480px * 480px Smart Screen"
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page
ota:
  - platform: esphome

logger:
  level: DEBUG

api:
  on_client_connected:
    - script.execute: time_update

time:
  - platform: homeassistant
    id: system_time

packages:
  # Generic configuration for ESP32 screens
  # All the colors
  colors: !include esphome-lvgl-panel/common/palette_dark.yaml
  #colors: !include esphome-lvgl-panel/common/palette_light.yaml
  # Fonts you need
  fonts: !include esphome-lvgl-panel/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-lvgl-panel/common/mdi_glyph_substitutions.yaml
  # SDL has no Wi-Fi wifi: 
  wifi: !include esphome-lvgl-panel/common/wifi.yaml
  time: !include esphome-lvgl-panel/common/time_sntp.yaml
  # Some basic sensors
  sensors: !include esphome-lvgl-panel/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include esphome-lvgl-panel/common/theme_style.yaml
  # Include if your touch screen has a backlight. Also sets the time from HA
  backlight: !include esphome-lvgl-panel/common/backlight_time.yaml
  # Harware description file
  hardware: !include esphome-lvgl-panel/hardware/guition-esp32-s3-4848s040.yaml

  # Basic boot screen with ESPHome logo and device diagnostic info
  loading_screen: !include esphome-lvgl-panel/pages/loading_480px.yaml
  info_screen: !include esphome-lvgl-panel/pages/info.yaml

  # Weather packages
  # Display weather forecast using direct HA action (no template sensor needed!)
  # Icons are included automatically in the action file
  weather_forecast_80: !include
    file: esphome-lvgl-panel/modules/weather/weather.yaml
    vars:
      size: 80
      weather_entity: weather.met_office_totton

# Styles for Weather forecast
.forecast_styles:
  - &now_forecast_obj_base
    width: 100%
    height: SIZE_CONTENT
    bg_color: color_background
    radius: 3
    pad_top: 2
    pad_bottom: 2
    layout:
      type: flex
      flex_flow: COLUMN
      flex_align_cross: center
      flex_align_track: center
      pad_column: 0
      pad_row: 2

  - &forecast_obj_base
    height: SIZE_CONTENT
    width: SIZE_CONTENT
    radius: 3
    pad_top: 2
    pad_bottom: 2
    layout:
      type: flex
      flex_flow: COLUMN
      flex_align_cross: center
      flex_align_track: center
      pad_column: 0
      pad_row: 2

  - &forecast_label_base
    text_font: font_body_24
    height: SIZE_CONTENT

  - &forecast_label_base_lo
    height: SIZE_CONTENT
    text_font: font_body_20
    text_color: dodgerblue

  - &forecast_image_base
    height: SIZE_CONTENT

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: current_time
          text: !lambda 'return id(system_time).now().strftime("%H:%M");'
      - lvgl.label.update:
          id: month_day
          text: !lambda |- # Month Day
            auto time = id(system_time).now();
            int day = time.day_of_month;
            char strftime_buf[64];
            snprintf(strftime_buf, sizeof(strftime_buf), "%s %d", time.strftime("%B").c_str(), day);
            return {strftime_buf};

text_sensor:
  - platform: homeassistant
    entity_id: sensor.leaf_battery_level
    id: leaf_battery_level
    on_value:
      then:
        - lambda: |-
            int level = atoi(id(leaf_battery_level).state.c_str());

            char buf[8];
            snprintf(buf, sizeof(buf), "%d%%", level);

            // id(ev_battery_level) is an lv_obj_t* (LVGL label object)
            lv_obj_t *label = id(ev_battery_level);

            // Update label text
            lv_label_set_text(label, buf);

            // Pick a colour (Material-ish)
            uint32_t hex =
              (level >= 40) ? 0x4CAF50 :   // green
              (level >= 15) ? 0xFFB300 :   // amber
                              0xE53935;    // red

            // Apply text colour
            lv_obj_set_style_text_color(label, lv_color_hex(hex), LV_PART_MAIN);

  - platform: homeassistant
    entity_id: sensor.leaf_range_ac_off
    id: leaf_range
    on_value:
      then:
      - lvgl.label.update:
          id: ev_range
          text: !lambda |-
            float range = atof(id(leaf_range).state.c_str());
            char buf[16];
            snprintf(buf, sizeof(buf), "%.0f miles", range);
            return std::string(buf);

image:
  rgb565:
    alpha_channel:
      - file: esphome-lvgl-panel/assets/images/car_outline_${display_mode}.svg
        id: car_outline_dark_200
        resize: 200x200

lvgl:
  pages:
    - id: main_page
      layout: 9x4
      styles: page_style
      <<: !include esphome-lvgl-panel/modules/swipe_navigation/swipe_navigation.yaml
      bg_color: color_background
      widgets:
        - container:
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_row_span: 3
            grid_cell_column_span: 2
            layout:
              type: flex
              flex_flow: COLUMN
              flex_align_main: center
              flex_align_cross: center
              pad_row: 2
            widgets:
              - label:
                  id: current_time
                  width: 100%
                  text_align: center
                  text_font: font_display_72
                  pad_bottom: -6   # <-- key adjustment
              - label:
                  id: month_day
                  width: 100%
                  text_align: center
                  text_font: font_body_24

        - container:
            id: ev_container
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 0
            grid_cell_column_pos: 2
            grid_cell_row_span: 3
            grid_cell_column_span: 2

            bg_color: color_background

            layout:
              type: flex
              flex_flow: COLUMN
              flex_align_cross: center
              flex_align_main: center
              pad_row: 6

            widgets:
              # ---- Car + % overlay ----
              - obj:
                  id: ev_car_overlay
                  width: SIZE_CONTENT
                  height: SIZE_CONTENT
                  bg_opa: TRANSP

                  widgets:
                    - image:
                        id: ev_car_icon
                        src: car_outline_dark_200
                        align: center

                    - label:
                        id: ev_battery_level
                        text: "--%"
                        align: center
                        x: 12       # tweak this
                        y: -3       # tweak this
                        text_font: font_body_32
                        text_color: color_primary_text
                        text_align: center

              # ---- Range below car ----
              - label:
                  id: ev_range
                  text: "--- miles"
                  text_font: font_body_24
                  text_color: color_secondary_text
                  text_align: center


        - container:
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 3
            grid_cell_column_pos: 0
            grid_cell_row_span: 3
            grid_cell_column_span: 2
            #outline_width: 1   # debug
            #outline_color: red # debug
            widgets:
              - obj:
                  <<: *now_forecast_obj_base
                  widgets:
                    - label:
                        text: "Now"
                        text_color: color_primary_text
                        <<: *forecast_label_base
                    - image:
                        id: weather_condition_icon
                        src: unknown_80
                    - label:
                        id: weather_temperature_today
                        <<: *forecast_label_base
                        text: "---°"
                        text_color: color_primary_text

        - container:
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 6
            grid_cell_column_pos: 0
            grid_cell_row_span: 3
            grid_cell_column_span: 4
            #outline_width: 1   # debug code - This is for visualizing boundries remove for production
            #outline_color: red # debug code - This is for visualizing boundries remove for production
            layout: 1x4
            widgets:
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  widgets:
                    - label:
                        id: forecast_day_0
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_0
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_0
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_0
                              <<: *forecast_label_base_lo
                              text: "---°"
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  widgets:
                    - label:
                        id: forecast_day_1
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_1
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_1
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_1
                              <<: *forecast_label_base_lo
                              text: "---°"
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  widgets:
                    - label:
                        id: forecast_day_2
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_2
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_2
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_2
                              <<: *forecast_label_base_lo
                              text: "---°"
              - obj:
                  <<: *forecast_obj_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 3
                  widgets:
                    - label:
                        id: forecast_day_3
                        <<: *forecast_label_base
                        text: ???
                    - image:
                        id: forecast_condition_icon_3
                        <<: *forecast_label_base
                        src: unknown_80
                    - container:
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_cross: center
                          pad_column: 4
                        widgets:
                          - label:
                              id: forecast_temperature_hi_3
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              text: "/"
                              <<: *forecast_label_base
                          - label:
                              id: forecast_temperature_lo_3
                              <<: *forecast_label_base_lo
                              text: "---°"