---
# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: font_body_20
  display_mode: dark   # or light
  text_color: color_primary_text
  bg_color: color_background
  button_on_color: color_accent
  button_off_color: color_outline
  icon_on_color: color_accent
  icon_off_color: color_secondary_text
  label_on_color: color_primary_text
  label_off_color: color_secondary_text
  button_text_color: color_primary_text

  device_name: "guition-4848s040"
  device_friendly_name: "Guition 4848s040"
  device_comment: "Guition ESP32-S3-4848S040 480px * 480px Smart Screen"

packages:
  # Infrastructure
  environment: !include esphome-lvgl-panel/common/environment.yaml
  hardware: !include esphome-lvgl-panel/hardware/guition-esp32-s3-4848s040.yaml

  # Some basic sensors
  sensors: !include esphome-lvgl-panel/sensors/sensors_base.yaml

  # Generic configuration for ESP32 screens
  # All the colors
  colors: !include esphome-lvgl-panel/common/colors_dark.yaml
  #colors: !include esphome-lvgl-panel/common/colors_light.yaml
  palette: !include esphome-lvgl-panel/common/palette.yaml

  # Fonts you need
  fonts: !include esphome-lvgl-panel/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-lvgl-panel/common/mdi_glyph_substitutions.yaml
  
  # Styles + Themes
  theme_style: !include esphome-lvgl-panel/common/theme_style.yaml
  # Include if your touch screen has a backlight. Also sets the time from HA

  backlight:
    !include
    file: esphome-lvgl-panel/modules/backlight/backlight_core.yaml
    vars:
      touchscreen_idle_behavior: "dim"

  # Basic boot screen with ESPHome logo and device diagnostic info
  boot_screen: !include esphome-lvgl-panel/modules/boot_screen/boot_screen_core.yaml

  info_screen: !include esphome-lvgl-panel/pages/info.yaml

  time_date_widget:
    !include
    file: esphome-lvgl-panel/modules/time_date/time_date_core.yaml

  ev_widget:
    !include
    file: esphome-lvgl-panel/modules/ev/ev_core.yaml
    vars:
      battery_level_entity: sensor.leaf_battery_level
      range_entity: sensor.leaf_range_ac_off
      charging_state_entity: binary_sensor.leaf_charging

  # Weather packages
  # Display weather today/forecast using direct HA action (no template sensor needed!)
  weather_icons: !include esphome-lvgl-panel/modules/weather/weather_icons.yaml
  weather_core: !include
    file: esphome-lvgl-panel/modules/weather/weather_core.yaml
    vars:
      weather_entity: weather.met_office_totton
      enable_today: "true"
      enable_forecast: "true"
      refresh_minutes: "15"

  climate_core: !include
    file: esphome-lvgl-panel/modules/climate/climate_core.yaml
    vars:
      climate_entity: climate.nest
      enable_temp_widget: "true"
      enable_humidity_widget: "true"
      humidity_warn_level: "70"
      refresh_interval: "30s"    
      enable_temp_override: "true"
      temp_override_entity: "sensor.timmerflotte_temp_hmd_sensor_temperature_2"
      enable_humidity_override: "true"
      humidity_override_entity: "sensor.timmerflotte_temp_hmd_sensor_humidity_2"

lvgl:
  pages:
    !include esphome-lvgl-panel/pages/main_page.yaml

