---
# Substitution variables used through the codebase
substitutions:
  device_name: "guition-4848s040"
  device_friendly_name: "Guition 4848s040"
  device_comment: "Guition ESP32-S3-4848S040 480px * 480px Smart Screen"
  display_mode: dark   # or light

packages:
  # Base config
  base: !include esphome-lvgl-panel/common/panel_base.yaml

  # Color theme
  colors: !include esphome-lvgl-panel/common/colors_dark.yaml
  #colors: !include esphome-lvgl-panel/common/colors_light.yaml

  backlight: !include esphome-lvgl-panel/modules/backlight/backlight_core.yaml

  time_date_widget: !include esphome-lvgl-panel/modules/time_date/time_date_core.yaml

  ev_widget: !include esphome-lvgl-panel/modules/ev/ev_core.yaml

  weather_icons: !include esphome-lvgl-panel/modules/weather/weather_icons.yaml
  weather_core: !include
    file: esphome-lvgl-panel/modules/weather/weather_core.yaml
    vars:
      weather_entity: weather.met_office_totton

  climate_core: !include
    file: esphome-lvgl-panel/modules/climate/climate_core.yaml
    #vars:
    #  enable_temp_override: "true"
    #  temp_override_entity: "sensor.timmerflotte_temp_hmd_sensor_temperature_2"
    #  enable_humidity_override: "true"
    #  humidity_override_entity: "sensor.timmerflotte_temp_hmd_sensor_humidity_2"

  # 1. Define the base page first
  living_room_base: !include esphome-lvgl-panel/pages/living_room.yaml
  
  # 2. Extend it with buttons second
  #living_room_content: !include esphome-lvgl-panel/pages/living_room_buttons.yaml
  
  main_page: !include esphome-lvgl-panel/pages/main_page.yaml

# Crucial: If you have "lvgl: pages:" here with nothing under it, 
# it might overwrite the work done in the packages. 
# Either list all pages here or leave it out if the packages handle it.
lvgl:

