---
# Weather (Home Assistant) — Now + Daily Forecast (optional)
#
# This module fetches weather data directly from Home Assistant using:
#   weather.get_forecasts
#
# ✅ No HA template sensors needed.
# ✅ Single service call can update BOTH:
#   - "Today / Now" (condition icon + current temperature)
#   - "Forecast" (4-day daily forecast)
#
# ------------------------------------------------------------------------------
# Vars (optional)
# ------------------------------------------------------------------------------
# weather_entity:
#   Weather entity id in Home Assistant.
#   Default: weather.home
#
# enable_today:
#   "true" / "false" (string, because substitutions are strings)
#   If true: updates Today/Now widgets (weather_condition_icon + weather_temperature_today)
#   Default: "true"
#
# enable_forecast:
#   "true" / "false"
#   If true: updates Forecast widgets (forecast_day_0..3 etc.)
#   Default: "true"
#
# refresh_minutes:
#   How often to refresh (minutes). Default: "15"
#
# ------------------------------------------------------------------------------
# Widget IDs expected (only if that section enabled)
# ------------------------------------------------------------------------------
# Today / Now widgets (enable_today: "true"):
#   - weather_condition_icon  (lvgl image)
#   - weather_temperature_today (lvgl label)
#
# Forecast widgets (enable_forecast: "true"):
#   - forecast_day_0..3 (lvgl label)
#   - forecast_temperature_hi_0..3 (lvgl label)
#   - forecast_temperature_lo_0..3 (lvgl label)
#   - forecast_condition_icon_0..3 (lvgl image)
#
# ------------------------------------------------------------------------------
# Icon Image IDs expected (must exist in your `image:` section)
# ------------------------------------------------------------------------------
# clear_night, cloudy, exceptional, fog, hail, lightning, lightning_rainy,
# partlycloudy, pouring, rainy, snowy, snowy_rainy, sunny, windy, unknown, unavailable
# ------------------------------------------------------------------------------

substitutions:
  enable_today: "true"
  enable_forecast: "true"
  refresh_minutes: "15"

# ------------------------------------------------------------------------------
# Refresh triggers
# ------------------------------------------------------------------------------
time:
  - platform: homeassistant
    on_time:
      # Every N minutes, on the minute boundary
      - minutes: "/${refresh_minutes}"
        seconds: 0
        then:
          - script.execute: fetch_weather

api:
  on_client_connected:
    - delay: 3s
    - script.execute: fetch_weather

# ------------------------------------------------------------------------------
# Core: one script = one HA call = update enabled sections
# ------------------------------------------------------------------------------
script:
  - id: fetch_weather
    then:
      - logger.log:
          level: INFO
          format: "Requesting weather (now + daily forecast) from Home Assistant..."
      - homeassistant.action:
          action: weather.get_forecasts
          data:
            type: daily
            entity_id: ${weather_entity | default("weather.home")}
          capture_response: true

          # We return a single JSON object:
          #   { now: { condition, temp }, forecast: [ {day, condition, hi, lo}, ... ] }
          response_template: >-
            {% set e = "${weather_entity | default('weather.home')}" %}
            {% set fc = response[e]["forecast"] %}
            {% set ns = namespace(out=[]) %}

            {# "Now" comes from the weather entity state/attributes #}
            {% set now_cond = states(e) %}
            {% set now_temp = state_attr(e, "temperature") %}

            {# 4-day forecast #}
            {% for i in range(0, 4) %}
              {% set f = fc[i] if fc is defined and fc|length > i else dict() %}
              {% set ns.out = ns.out + [ {
                "day": (as_timestamp(f.datetime) | timestamp_custom('%a')) if f.datetime is defined else "—",
                "condition": (f.condition | default('unknown')),
                "hi": (f.temperature | default(0)),
                "lo": (f.templow | default(0))
              } ] %}
            {% endfor %}

            {{ {
              "now": {
                "condition": now_cond | default("unknown"),
                "temp": now_temp | default(0)
              },
              "forecast": ns.out
            } | tojson }}

          on_success:
            - logger.log:
                level: INFO
                format: "Weather fetch OK: updating widgets"

            - lambda: |-
                // response["response"] is the JSON created by response_template
                auto root = response["response"];
                auto now = root["now"];
                auto arr = root["forecast"];  // JSON array

                auto pick_icon = [&](const std::string &c) -> esphome::image::Image* {
                  if (c == "clear-night") return id(clear_night);
                  if (c == "cloudy") return id(cloudy);
                  if (c == "exceptional") return id(exceptional);
                  if (c == "fog") return id(fog);
                  if (c == "hail") return id(hail);
                  if (c == "lightning") return id(lightning);
                  if (c == "lightning-rainy") return id(lightning_rainy);
                  if (c == "partlycloudy") return id(partlycloudy);
                  if (c == "pouring") return id(pouring);
                  if (c == "rainy") return id(rainy);
                  if (c == "snowy") return id(snowy);
                  if (c == "snowy-rainy") return id(snowy_rainy);
                  if (c == "sunny") return id(sunny);
                  if (c == "windy" || c == "windy-variant") return id(windy);
                  if (c == "unavailable") return id(unavailable);
                  return id(unknown);
                };

                auto fmt_deg = [](float v) -> std::string {
                  int ti = (int) lroundf(v);
                  char buf[8];
                  snprintf(buf, sizeof(buf), "%d°", ti);
                  return std::string(buf);
                };

                // ─────────────────────────────────────────────────────────────
                // TODAY (Now)
                // ─────────────────────────────────────────────────────────────
                if (${enable_today | default("true")}) {
                  std::string now_cond = now["condition"].as<std::string>();
                  float now_temp = now["temp"].as<float>();

                  // icon
                  lv_obj_t *img = id(weather_condition_icon);
                  lv_img_set_src(img, pick_icon(now_cond));

                  // temperature label
                  std::string t = fmt_deg(now_temp);
                  lv_obj_t *lbl = id(weather_temperature_today);
                  lv_label_set_text(lbl, t.c_str());
                }

                // Helper to set a single forecast row
                auto set_row = [&](int idx,
                                  lv_obj_t *day_lbl,
                                  lv_obj_t *hi_lbl,
                                  lv_obj_t *lo_lbl,
                                  lv_obj_t *img) {
                  auto o = arr[idx];
                  std::string day = o["day"].as<std::string>();
                  std::string cond = o["condition"].as<std::string>();
                  float hi = o["hi"].as<float>();
                  float lo = o["lo"].as<float>();

                  lv_label_set_text(day_lbl, day.c_str());

                  std::string hi_s = fmt_deg(hi);
                  std::string lo_s = fmt_deg(lo);
                  lv_label_set_text(hi_lbl, hi_s.c_str());
                  lv_label_set_text(lo_lbl, lo_s.c_str());

                  lv_img_set_src(img, pick_icon(cond));
                };

                // ─────────────────────────────────────────────────────────────
                // FORECAST (4 days)
                // ─────────────────────────────────────────────────────────────
                if (${enable_forecast | default("true")}) {
                  set_row(0, id(forecast_day_0), id(forecast_temperature_hi_0), id(forecast_temperature_lo_0), id(forecast_condition_icon_0));
                  set_row(1, id(forecast_day_1), id(forecast_temperature_hi_1), id(forecast_temperature_lo_1), id(forecast_condition_icon_1));
                  set_row(2, id(forecast_day_2), id(forecast_temperature_hi_2), id(forecast_temperature_lo_2), id(forecast_condition_icon_2));
                  set_row(3, id(forecast_day_3), id(forecast_temperature_hi_3), id(forecast_temperature_lo_3), id(forecast_condition_icon_3));
                }

          on_error:
            - logger.log:
                level: ERROR
                format: "Failed to fetch weather from Home Assistant"