---
# EV Status widget
#
# Shows charge, range and charge indicator
#
# vars:
#   page_entity: lvgl page
#   row_pos: grid_cell_row_pos
#   column_pos: grid_cell_column_pos
#   row_span: grid_cell_row_span
#   column_span: grid_cell_column_span
#   battery_level_entity: eg. sensor.leaf_battery_level
#   range_entity: eg. sensor.leaf_range_ac_off
#   charging_state_entity: eg. binary_sensor.leaf_charging

script:
  - id: render_ev_battery
    then:
      - lambda: |-
          // Battery %
          int level = atoi(id(leaf_battery_level).state.c_str());
          bool charging = id(leaf_charging).state;

          if (charging) {
            lv_obj_clear_flag(id(ev_charge_icon), LV_OBJ_FLAG_HIDDEN);
          } else {
            lv_obj_add_flag(id(ev_charge_icon), LV_OBJ_FLAG_HIDDEN);
          }

          // Build label text
          char buf[16];
          snprintf(buf, sizeof(buf), "%d%%", level);
          lv_obj_t *label = id(ev_battery_level);
          lv_label_set_text(label, buf);

          uint32_t hex;
          if (charging) {
            hex = 0x2196F3; // Material-ish blue
          } else {
            hex =
              (level >= 40) ? 0x4CAF50 :   // green
              (level >= 15) ? 0xFFB300 :   // amber
                             0xE53935;    // red
          }

          lv_obj_set_style_text_color(label, lv_color_hex(hex), LV_PART_MAIN);

text_sensor:
  - platform: homeassistant
    entity_id: ${battery_level_entity | default("sensor.leaf_battery_level")}
    id: leaf_battery_level
    on_value:
      then:
        - script.execute: render_ev_battery

  - platform: homeassistant
    entity_id: ${range_entity | default("sensor.leaf_range_ac_off")}
    id: leaf_range
    on_value:
      then:
      - lvgl.label.update:
          id: ev_range
          text: !lambda |-
            float range = atof(id(leaf_range).state.c_str());
            char buf[16];
            snprintf(buf, sizeof(buf), "%.0f miles", range);
            return std::string(buf);

binary_sensor:
  - platform: homeassistant
    entity_id: ${charging_state_entity | default("binary_sensor.leaf_charging")}
    id: leaf_charging
    on_state:
      then:
        - script.execute: render_ev_battery

image:
  rgb565:
    alpha_channel:
      - file: esphome-lvgl-panel/modules/ev/assets/images/car_outline_${display_mode}.svg
        id: car_outline_dark_200
        resize: 200x200


lvgl:
  pages:
    - id: ${page_entity | default("main_page")}
      widgets:
        - container:
            id: ev_container
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: ${row_pos | default("0")}
            grid_cell_column_pos: ${column_pos | default("0")}
            grid_cell_row_span: ${row_span | default("6")}
            grid_cell_column_span: ${column_span | default("4")}

            bg_color: color_background

            layout:
              type: flex
              flex_flow: COLUMN
              flex_align_cross: center
              flex_align_main: center
              pad_row: 6

            widgets:
              # ---- Car + % overlay ----
              - obj:
                  id: ev_car_overlay
                  width: SIZE_CONTENT
                  height: SIZE_CONTENT
                  bg_opa: TRANSP

                  widgets:
                    - image:
                        id: ev_car_icon
                        src: car_outline_dark_200
                        align: center
                    - obj:
                        id: ev_battery_row
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        bg_opa: TRANSP
                        align: center
                        x: 6
                        y: -3
                        layout:
                          type: flex
                          flex_flow: ROW
                          flex_align_main: center
                          flex_align_cross: center
                          pad_column: 0
                        widgets:
                          - label:
                              id: ev_charge_icon
                              text: "${mdi_lightning_bolt}"
                              text_font: font_mdi_32
                              text_color: 0x2196F3
                              hidden: true
                              pad_right: -6
                          - label:
                              id: ev_battery_level
                              text: "--%"
                              text_font: font_body_32
                              text_color: color_primary_text
                              text_align: center

              # ---- Range below car ----
              - label:
                  id: ev_range
                  text: "--- miles"
                  text_font: font_body_24
                  text_color: color_secondary_text
                  text_align: center