---
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: ${device_comment}

# TIME provider (Home Assistant)
## Provides:
#   id: system_time
time:
  - platform: homeassistant
    id: system_time

# Common Sun provider
# Enables use of `sun.is_above_horizon` conditions in any module.
sun:
  latitude: !secret latitude
  longitude: !secret longitude

script:
  - id: touchscreen_touched
    then:
      - lambda: 'return;'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome

api:

logger:
  level: DEBUG