## Allows using mdi icons in esphome configs without having to look up the 
## unicode value. Uses the substitution engine to substitute the icon with 
## the unicode. This means it is limited to a valid substitution format
## So instead of the home assistant mdi: way, icons are prefixed with mdi_. 
## Slashes are also not allowed, so those are replaced with underscores as well.
## This is a minmal version compared to esphome-modular-lvgl-buttons to cut down
## complexity
---
substitutions:
  mdi_home_lightning_bolt: "\U000F1903"
  mdi_home_lightning_bolt_outline: "\U000F1904"
