---
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: ${device_comment}

# TIME provider (Home Assistant)
## Provides:
#   id: system_time
time:
  - platform: homeassistant
    id: system_time

# Common Sun provider
# Enables use of `sun.is_above_horizon` conditions in any module.
sun:
  latitude: !secret latitude
  longitude: !secret longitude

script:
  - id: touchscreen_touched
    then:
      - lambda: 'return;'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome

api:

logger:
  level: DEBUG

packages:
  # Board profile (THIS makes it Guition-specific)
  hardware: !include ../hardware/guition-esp32-s3-4848s040.yaml

  # Framework invariants
  palette: !include palette.yaml
  fonts: !include fonts.yaml
  glyphs: !include mdi_glyph_substitutions.yaml
  theme_style: !include theme_style.yaml

  # (optional) sensors — only if you audit/split UI hooks as discussed
  #sensors: !include ../sensors/sensors_base.yaml

  # Basic boot screen with ESPHome logo and device diagnostic info
  boot_screen: !include ../modules/boot_screen/boot_screen_core.yaml

  info_core: !include ../modules/info/info_core.yaml
  info_screen: !include ../pages/info.yaml